export const UserActionTypes = {
  FETCH_LOGIN_START: 'FETCH_LOGIN_START',
  FETCH_LOGIN_SUCCESS: 'FETCH_LOGIN_SUCCESS',
  FETCH_LOGIN_FAILED: 'FETCH_LOGIN_FAILED',
  FETCH_REGISTER_START: 'FETCH_REGISTER_START',
  FETCH_REGISTER_SUCCESS: 'FETCH_REGISTER_SUCCESS',
  LOGOUT: 'LOGOUT',
};
