name: Upload to Bunny Storage
env:
  environment: "development"
on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 18.20.0

      - name: Install dependencies
        run: npm ci

      - name: 'Create env file'
        run: |
          touch .env
          echo REACT_APP_API_URL_MS="https://bodega-store-dd3d3b32bb05.herokuapp.com/api/" >> .env
          echo REACT_APP_API_URL_PAYPAL="https://api-m.sandbox.paypal.com/v1" >> .env
          echo REACT_APP_PAYPAL_CLIENT_ID=${{ secrets.REACT_APP_PAYPAL_CLIENT_ID }} >> .env
          echo REACT_APP_API_URL_PAYPAL_PASSWORD=${{ secrets.REACT_APP_API_URL_PAYPAL_PASSWORD }} >> .env
          echo REACT_APP_GOOGLE_PAY_ENVIRONMENT=TEST >> .env
          echo REACT_APP_GOOGLE_ANALYTICS_MEASUREMENT_ID=${{ secrets.REACT_APP_GOOGLE_ANALYTICS_MEASUREMENT_ID }} >> .env
          echo KEYCLOAK_URL=${{ secrets.KEYCLOAK_URL }} >> .env
          echo KEYCLOAK_REALM=${{ secrets.KEYCLOAK_REALM }} >> .env
          echo KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }} >> .env
          echo KEYCLOAK_INIT_REDIRECT_URL=${{ secrets.KEYCLOAK_INIT_REDIRECT_URL }} >> .env
          cat .env

      - name: Build App
        run: npm run build:dev

      - name: Upload files to Bunny Storage
        uses: ayeressian/bunnycdn-storage-deploy@v2.4.0
        with:
          source: "dist"
          destination: "bodega-project"
          storageZoneName: "${{ secrets.BUNNY_ARANCIBIA_STORAGE_NAME }}"
          storagePassword: "${{ secrets.BUNNY_ARANCIBIA_STORAGE_PASSWORD }}"
          storageEndpoint: "sg.storage.bunnycdn.com"
          accessKey: "${{ secrets.BUNNY_API_ACCESS_KEY }}"
          pullZoneId: "${{ secrets.BUNNY_ARANCIBIA_PULL_ZONE_ID }}"
          upload: "true"
          remove: "false"
          purgePullZone: "true"
          purgePullZoneDelay: "5"
          maxRetries: "5"
  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 20.19.4

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Upload files to Bunny Storage
        uses: ayeressian/bunnycdn-storage-deploy@v2.4.0
        with:
          source: "storybook-static"
          destination: "storybook/bodega"
          storageZoneName: "${{ secrets.BUNNY_ARANCIBIA_STORAGE_NAME }}"
          storagePassword: "${{ secrets.BUNNY_ARANCIBIA_STORAGE_PASSWORD }}"
          storageEndpoint: "sg.storage.bunnycdn.com"
          accessKey: "${{ secrets.BUNNY_API_ACCESS_KEY }}"
          pullZoneId: "${{ secrets.BUNNY_ARANCIBIA_PULL_ZONE_ID }}"
          upload: "true"
          remove: "false"
          purgePullZone: "true"
          purgePullZoneDelay: "5"
          maxRetries: "5"
